version: "3.8"
services:
  auth-service:
    build: ./services/auth
    ports:
      - "3000:3000"
    environment:
      JWT_SECRET: JWLT_SECRET
    volumes:
      - ./services/auth:/app
      - auth_db:/app/auth.db
    depends_on:
      - auth_db

  chat-service:
    build: ./services/chat
    ports:
      - "3001:3001"
    volumes:
      - ./services/chat:/app
      - chat_db:/app/chat.db
    depends_on:
      - chat_db

  notification-service:
    build: ./services/notification
    ports:
      - "3002:3002"
    volumes:
      - ./services/notification:/app
    depends_on:
      - notification_db

  frontend:
    build: ./services/frontend
    ports:
      - "80:80"
volumes:
  auth_db:
  chat_db:
  notification_db: